-- ============================================================
--  WTC Challenge -- Oracle SQL Developer
--  Execute conectado ao schema do seu usuario (XEPDB1)
-- ============================================================

-- ============================================================
--  PARTE 1: DROP (ordem inversa das FKs)
-- ============================================================

BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_TASKS               CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_AUDIT_LOGS          CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_ANNOTATIONS         CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_CAMPAIGN_RECIPIENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_CAMPAIGNS           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_MESSAGES            CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_CLIENTS             CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_SEGMENTS            CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE WTC_USERS               CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TASKS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_AUDIT_LOGS';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ANNOTATIONS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CAMP_RECIP';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CAMPAIGNS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MESSAGES';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEGMENTS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USERS';        EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
--  PARTE 2: SEQUENCES
--  JPA usa GenerationType.SEQUENCE com esses nomes exatos
-- ============================================================

CREATE SEQUENCE SEQ_USERS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEGMENTS    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CLIENTS     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MESSAGES    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CAMPAIGNS   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CAMP_RECIP  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANNOTATIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT_LOGS  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TASKS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
--  PARTE 3: TABELAS
-- ============================================================

-- 1. Usuarios do sistema
CREATE TABLE WTC_USERS (
    ID         NUMBER(19)    PRIMARY KEY,
    NAME       VARCHAR2(150) NOT NULL,
    EMAIL      VARCHAR2(200) NOT NULL,
    PASSWORD   VARCHAR2(255) NOT NULL,
    ROLE       VARCHAR2(20)  NOT NULL,
    FCM_TOKEN  VARCHAR2(500),
    ACTIVE     NUMBER(1)     DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP     NOT NULL,
    UPDATED_AT TIMESTAMP     NOT NULL,
    CONSTRAINT uq_users_email  UNIQUE (EMAIL),
    CONSTRAINT ck_users_role   CHECK (ROLE   IN ('OPERATOR', 'CLIENT')),
    CONSTRAINT ck_users_active CHECK (ACTIVE IN (0, 1))
);

-- 2. Segmentos de clientes
CREATE TABLE WTC_SEGMENTS (
    ID          NUMBER(19)    PRIMARY KEY,
    NAME        VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CREATED_BY  NUMBER(19)    NOT NULL,
    CREATED_AT  TIMESTAMP     NOT NULL,
    UPDATED_AT  TIMESTAMP     NOT NULL,
    CONSTRAINT uq_segments_name    UNIQUE (NAME),
    CONSTRAINT fk_segments_created FOREIGN KEY (CREATED_BY) REFERENCES WTC_USERS(ID)
);

-- 3. Perfis de clientes
CREATE TABLE WTC_CLIENTS (
    ID         NUMBER(19)   PRIMARY KEY,
    USER_ID    NUMBER(19)   NOT NULL,
    SEGMENT_ID NUMBER(19),
    TAGS       VARCHAR2(500),
    SCORE      NUMBER(5,2)  DEFAULT 0,
    STATUS     VARCHAR2(20) DEFAULT 'ACTIVE',
    PHONE      VARCHAR2(30),
    COMPANY    VARCHAR2(200),
    CREATED_AT TIMESTAMP    NOT NULL,
    UPDATED_AT TIMESTAMP    NOT NULL,
    CONSTRAINT uq_clients_user    UNIQUE (USER_ID),
    CONSTRAINT fk_clients_user    FOREIGN KEY (USER_ID)    REFERENCES WTC_USERS(ID),
    CONSTRAINT fk_clients_segment FOREIGN KEY (SEGMENT_ID) REFERENCES WTC_SEGMENTS(ID),
    CONSTRAINT ck_clients_status  CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED', 'PROSPECT'))
);

-- 4. Mensagens de chat
CREATE TABLE WTC_MESSAGES (
    ID           NUMBER(19)     PRIMARY KEY,
    SENDER_ID    NUMBER(19)     NOT NULL,
    RECEIVER_ID  NUMBER(19),
    SEGMENT_ID   NUMBER(19),
    CONTENT      VARCHAR2(4000) NOT NULL,
    TYPE         VARCHAR2(20)   DEFAULT 'TEXT',
    STATUS       VARCHAR2(20)   DEFAULT 'SENT',
    DEEPLINK     VARCHAR2(500),
    SENT_AT      TIMESTAMP      NOT NULL,
    DELIVERED_AT TIMESTAMP,
    READ_AT      TIMESTAMP,
    CONSTRAINT fk_msg_sender   FOREIGN KEY (SENDER_ID)   REFERENCES WTC_USERS(ID),
    CONSTRAINT fk_msg_receiver FOREIGN KEY (RECEIVER_ID) REFERENCES WTC_USERS(ID),
    CONSTRAINT fk_msg_segment  FOREIGN KEY (SEGMENT_ID)  REFERENCES WTC_SEGMENTS(ID),
    CONSTRAINT ck_msg_type     CHECK (TYPE   IN ('TEXT', 'IMAGE', 'PROMO', 'INVITE', 'BANNER')),
    CONSTRAINT ck_msg_status   CHECK (STATUS IN ('SENT', 'DELIVERED', 'READ', 'FAILED'))
);

-- 5. Campanhas de push/notificacao
CREATE TABLE WTC_CAMPAIGNS (
    ID         NUMBER(19)     PRIMARY KEY,
    TITLE      VARCHAR2(200)  NOT NULL,
    BODY       VARCHAR2(4000) NOT NULL,
    TYPE       VARCHAR2(20)   DEFAULT 'PROMO',
    SEGMENT_ID NUMBER(19)     NOT NULL,
    CREATED_BY NUMBER(19)     NOT NULL,
    DEEPLINK   VARCHAR2(500),
    STATUS     VARCHAR2(20)   DEFAULT 'DRAFT',
    SENT_AT    TIMESTAMP,
    CREATED_AT TIMESTAMP      NOT NULL,
    CONSTRAINT fk_camp_segment FOREIGN KEY (SEGMENT_ID) REFERENCES WTC_SEGMENTS(ID),
    CONSTRAINT fk_camp_created FOREIGN KEY (CREATED_BY) REFERENCES WTC_USERS(ID),
    CONSTRAINT ck_camp_type    CHECK (TYPE   IN ('PROMO', 'INVITE', 'BANNER', 'COMUNICADO')),
    CONSTRAINT ck_camp_status  CHECK (STATUS IN ('DRAFT', 'SENT', 'FAILED'))
);

-- 6. Destinatarios de campanhas
CREATE TABLE WTC_CAMPAIGN_RECIPIENTS (
    ID           NUMBER(19)   PRIMARY KEY,
    CAMPAIGN_ID  NUMBER(19)   NOT NULL,
    CLIENT_ID    NUMBER(19)   NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'PENDING',
    SENT_AT      TIMESTAMP,
    DELIVERED_AT TIMESTAMP,
    READ_AT      TIMESTAMP,
    CONSTRAINT fk_recip_campaign FOREIGN KEY (CAMPAIGN_ID) REFERENCES WTC_CAMPAIGNS(ID),
    CONSTRAINT fk_recip_client   FOREIGN KEY (CLIENT_ID)   REFERENCES WTC_CLIENTS(ID),
    CONSTRAINT ck_recip_status   CHECK (STATUS IN ('PENDING', 'SENT', 'DELIVERED', 'READ', 'FAILED'))
);

-- 7. Anotacoes de operadores sobre clientes
CREATE TABLE WTC_ANNOTATIONS (
    ID          NUMBER(19)     PRIMARY KEY,
    CLIENT_ID   NUMBER(19)     NOT NULL,
    OPERATOR_ID NUMBER(19)     NOT NULL,
    CONTENT     VARCHAR2(2000) NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL,
    CONSTRAINT fk_annot_client   FOREIGN KEY (CLIENT_ID)   REFERENCES WTC_CLIENTS(ID),
    CONSTRAINT fk_annot_operator FOREIGN KEY (OPERATOR_ID) REFERENCES WTC_USERS(ID)
);

-- 8. Logs de auditoria
CREATE TABLE WTC_AUDIT_LOGS (
    ID         NUMBER(19)     PRIMARY KEY,
    USER_ID    NUMBER(19),
    ACTION     VARCHAR2(100)  NOT NULL,
    ENTITY     VARCHAR2(100),
    ENTITY_ID  NUMBER(19),
    DETAILS    VARCHAR2(4000),
    IP_ADDRESS VARCHAR2(50),
    CREATED_AT TIMESTAMP      NOT NULL,
    CONSTRAINT fk_audit_user FOREIGN KEY (USER_ID) REFERENCES WTC_USERS(ID)
);

-- 9. Tarefas vinculadas a mensagens
CREATE TABLE WTC_TASKS (
    ID          NUMBER(19)    PRIMARY KEY,
    MESSAGE_ID  NUMBER(19),
    ASSIGNED_TO NUMBER(19)    NOT NULL,
    CREATED_BY  NUMBER(19)    NOT NULL,
    TITLE       VARCHAR2(300) NOT NULL,
    STATUS      VARCHAR2(20)  DEFAULT 'OPEN',
    CREATED_AT  TIMESTAMP     NOT NULL,
    UPDATED_AT  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_task_message  FOREIGN KEY (MESSAGE_ID)  REFERENCES WTC_MESSAGES(ID),
    CONSTRAINT fk_task_assigned FOREIGN KEY (ASSIGNED_TO) REFERENCES WTC_USERS(ID),
    CONSTRAINT fk_task_created  FOREIGN KEY (CREATED_BY)  REFERENCES WTC_USERS(ID),
    CONSTRAINT ck_task_status   CHECK (STATUS IN ('OPEN', 'IN_PROGRESS', 'DONE'))
);

-- ============================================================
--  PARTE 4: USUARIO OPERADOR INICIAL
--  Login: admin@wtc.com  |  Senha: admin123
-- ============================================================

INSERT INTO WTC_USERS (ID, NAME, EMAIL, PASSWORD, ROLE, ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (
    SEQ_USERS.NEXTVAL,
    'Administrador',
    'admin@wtc.com',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
    'OPERATOR',
    1,
    SYSTIMESTAMP,
    SYSTIMESTAMP
);

COMMIT;
